name: cleanData
on: 
  workflow_dispatch
  

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - name: setup python
        uses: actions/setup-python@v4
        with:
            python-version: "3.10"
      - name: check version of python
        run: |
          pip install pandas
          python --version
          pip --version
          
      - name: clone code
        uses: actions/checkout@v4
      - name: Clean Data
        run: python cleandata.py
        
      -name: Train and Test Model
       run: python train_test_dataset.py 
